I am thrown when an argument is provided that is invalid. 